/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusRouteImport } from './routes/bus'
import { Route as CentreRegulationRouteImport } from './routes/centre-regulation'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EspaceEmployesRouteImport } from './routes/espace-employes'
import { Route as HistoireRouteImport } from './routes/histoire'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MesDemandesRouteImport } from './routes/mes-demandes'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as SuiviDemandesRouteImport } from './routes/suivi-demandes'
import { Route as TraficRouteImport } from './routes/trafic'
import { Route as ApiAuditLogsRouteImport } from './routes/api/audit-logs'
import { Route as ApiDeparturesRouteImport } from './routes/api/departures'
import { Route as ApiIncidentsRouteImport } from './routes/api/incidents'
import { Route as ApiLostFoundRouteImport } from './routes/api/lost-found'
import { Route as ApiPvRouteImport } from './routes/api/pv'
import { Route as ApiTrafficRouteImport } from './routes/api/traffic'
import { Route as GaresStationRouteImport } from './routes/gares/$station'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api/public/contact/submit'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'
import { Route as ApiPublicDiscordLoginRouteImport } from './routes/api/public/discord/login'
import { Route as ApiPublicDiscordLogoutRouteImport } from './routes/api/public/discord/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreRegulationRoute = CentreRegulationRouteImport.update({
  id: '/centre-regulation',
  path: '/centre-regulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceEmployesRoute = EspaceEmployesRouteImport.update({
  id: '/espace-employes',
  path: '/espace-employes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoireRoute = HistoireRouteImport.update({
  id: '/histoire',
  path: '/histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MesDemandesRoute = MesDemandesRouteImport.update({
  id: '/mes-demandes',
  path: '/mes-demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviDemandesRoute = SuiviDemandesRouteImport.update({
  id: '/suivi-demandes',
  path: '/suivi-demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const TraficRoute = TraficRouteImport.update({
  id: '/trafic',
  path: '/trafic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogsRoute = ApiAuditLogsRouteImport.update({
  id: '/api/audit-logs',
  path: '/api/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeparturesRoute = ApiDeparturesRouteImport.update({
  id: '/api/departures',
  path: '/api/departures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsRoute = ApiIncidentsRouteImport.update({
  id: '/api/incidents',
  path: '/api/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLostFoundRoute = ApiLostFoundRouteImport.update({
  id: '/api/lost-found',
  path: '/api/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPvRoute = ApiPvRouteImport.update({
  id: '/api/pv',
  path: '/api/pv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrafficRoute = ApiTrafficRouteImport.update({
  id: '/api/traffic',
  path: '/api/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const GaresStationRoute = GaresStationRouteImport.update({
  id: '/gares/$station',
  path: '/gares/$station',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact/submit',
  path: '/api/public/contact/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordLoginRoute = ApiPublicDiscordLoginRouteImport.update({
  id: '/api/public/discord/login',
  path: '/api/public/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordLogoutRoute = ApiPublicDiscordLogoutRouteImport.update({
  id: '/api/public/discord/logout',
  path: '/api/public/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/centre-regulation': typeof CentreRegulationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/espace-employes': typeof EspaceEmployesRoute
  '/histoire': typeof HistoireRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-demandes': typeof MesDemandesRoute
  '/recrutement': typeof RecrutementRoute
  '/suivi-demandes': typeof SuiviDemandesRoute
  '/trafic': typeof TraficRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/departures': typeof ApiDeparturesRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/lost-found': typeof ApiLostFoundRoute
  '/api/pv': typeof ApiPvRoute
  '/api/traffic': typeof ApiTrafficRoute
  '/gares/$station': typeof GaresStationRoute
  '/api/public/contact/submit': typeof ApiPublicContactSubmitRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/centre-regulation': typeof CentreRegulationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/espace-employes': typeof EspaceEmployesRoute
  '/histoire': typeof HistoireRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-demandes': typeof MesDemandesRoute
  '/recrutement': typeof RecrutementRoute
  '/suivi-demandes': typeof SuiviDemandesRoute
  '/trafic': typeof TraficRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/departures': typeof ApiDeparturesRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/lost-found': typeof ApiLostFoundRoute
  '/api/pv': typeof ApiPvRoute
  '/api/traffic': typeof ApiTrafficRoute
  '/gares/$station': typeof GaresStationRoute
  '/api/public/contact/submit': typeof ApiPublicContactSubmitRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/centre-regulation': typeof CentreRegulationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/espace-employes': typeof EspaceEmployesRoute
  '/histoire': typeof HistoireRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-demandes': typeof MesDemandesRoute
  '/recrutement': typeof RecrutementRoute
  '/suivi-demandes': typeof SuiviDemandesRoute
  '/trafic': typeof TraficRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/departures': typeof ApiDeparturesRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/lost-found': typeof ApiLostFoundRoute
  '/api/pv': typeof ApiPvRoute
  '/api/traffic': typeof ApiTrafficRoute
  '/gares/$station': typeof GaresStationRoute
  '/api/public/contact/submit': typeof ApiPublicContactSubmitRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus'
    | '/centre-regulation'
    | '/confidentialite'
    | '/contact'
    | '/espace-employes'
    | '/histoire'
    | '/mentions-legales'
    | '/mes-demandes'
    | '/recrutement'
    | '/suivi-demandes'
    | '/trafic'
    | '/api/audit-logs'
    | '/api/departures'
    | '/api/incidents'
    | '/api/lost-found'
    | '/api/pv'
    | '/api/traffic'
    | '/gares/$station'
    | '/api/public/contact/submit'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus'
    | '/centre-regulation'
    | '/confidentialite'
    | '/contact'
    | '/espace-employes'
    | '/histoire'
    | '/mentions-legales'
    | '/mes-demandes'
    | '/recrutement'
    | '/suivi-demandes'
    | '/trafic'
    | '/api/audit-logs'
    | '/api/departures'
    | '/api/incidents'
    | '/api/lost-found'
    | '/api/pv'
    | '/api/traffic'
    | '/gares/$station'
    | '/api/public/contact/submit'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
  id:
    | '__root__'
    | '/'
    | '/bus'
    | '/centre-regulation'
    | '/confidentialite'
    | '/contact'
    | '/espace-employes'
    | '/histoire'
    | '/mentions-legales'
    | '/mes-demandes'
    | '/recrutement'
    | '/suivi-demandes'
    | '/trafic'
    | '/api/audit-logs'
    | '/api/departures'
    | '/api/incidents'
    | '/api/lost-found'
    | '/api/pv'
    | '/api/traffic'
    | '/gares/$station'
    | '/api/public/contact/submit'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusRoute: typeof BusRoute
  CentreRegulationRoute: typeof CentreRegulationRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  EspaceEmployesRoute: typeof EspaceEmployesRoute
  HistoireRoute: typeof HistoireRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MesDemandesRoute: typeof MesDemandesRoute
  RecrutementRoute: typeof RecrutementRoute
  SuiviDemandesRoute: typeof SuiviDemandesRoute
  TraficRoute: typeof TraficRoute
  ApiAuditLogsRoute: typeof ApiAuditLogsRoute
  ApiDeparturesRoute: typeof ApiDeparturesRoute
  ApiIncidentsRoute: typeof ApiIncidentsRoute
  ApiLostFoundRoute: typeof ApiLostFoundRoute
  ApiPvRoute: typeof ApiPvRoute
  ApiTrafficRoute: typeof ApiTrafficRoute
  GaresStationRoute: typeof GaresStationRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicDiscordLoginRoute: typeof ApiPublicDiscordLoginRoute
  ApiPublicDiscordLogoutRoute: typeof ApiPublicDiscordLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre-regulation': {
      id: '/centre-regulation'
      path: '/centre-regulation'
      fullPath: '/centre-regulation'
      preLoaderRoute: typeof CentreRegulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-employes': {
      id: '/espace-employes'
      path: '/espace-employes'
      fullPath: '/espace-employes'
      preLoaderRoute: typeof EspaceEmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histoire': {
      id: '/histoire'
      path: '/histoire'
      fullPath: '/histoire'
      preLoaderRoute: typeof HistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-demandes': {
      id: '/mes-demandes'
      path: '/mes-demandes'
      fullPath: '/mes-demandes'
      preLoaderRoute: typeof MesDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi-demandes': {
      id: '/suivi-demandes'
      path: '/suivi-demandes'
      fullPath: '/suivi-demandes'
      preLoaderRoute: typeof SuiviDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trafic': {
      id: '/trafic'
      path: '/trafic'
      fullPath: '/trafic'
      preLoaderRoute: typeof TraficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs': {
      id: '/api/audit-logs'
      path: '/api/audit-logs'
      fullPath: '/api/audit-logs'
      preLoaderRoute: typeof ApiAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departures': {
      id: '/api/departures'
      path: '/api/departures'
      fullPath: '/api/departures'
      preLoaderRoute: typeof ApiDeparturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents': {
      id: '/api/incidents'
      path: '/api/incidents'
      fullPath: '/api/incidents'
      preLoaderRoute: typeof ApiIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lost-found': {
      id: '/api/lost-found'
      path: '/api/lost-found'
      fullPath: '/api/lost-found'
      preLoaderRoute: typeof ApiLostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pv': {
      id: '/api/pv'
      path: '/api/pv'
      fullPath: '/api/pv'
      preLoaderRoute: typeof ApiPvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traffic': {
      id: '/api/traffic'
      path: '/api/traffic'
      fullPath: '/api/traffic'
      preLoaderRoute: typeof ApiTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gares/$station': {
      id: '/gares/$station'
      path: '/gares/$station'
      fullPath: '/gares/$station'
      preLoaderRoute: typeof GaresStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact/submit': {
      id: '/api/public/contact/submit'
      path: '/api/public/contact/submit'
      fullPath: '/api/public/contact/submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/login': {
      id: '/api/public/discord/login'
      path: '/api/public/discord/login'
      fullPath: '/api/public/discord/login'
      preLoaderRoute: typeof ApiPublicDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/logout': {
      id: '/api/public/discord/logout'
      path: '/api/public/discord/logout'
      fullPath: '/api/public/discord/logout'
      preLoaderRoute: typeof ApiPublicDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusRoute: BusRoute,
  CentreRegulationRoute: CentreRegulationRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  EspaceEmployesRoute: EspaceEmployesRoute,
  HistoireRoute: HistoireRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MesDemandesRoute: MesDemandesRoute,
  RecrutementRoute: RecrutementRoute,
  SuiviDemandesRoute: SuiviDemandesRoute,
  TraficRoute: TraficRoute,
  ApiAuditLogsRoute: ApiAuditLogsRoute,
  ApiDeparturesRoute: ApiDeparturesRoute,
  ApiIncidentsRoute: ApiIncidentsRoute,
  ApiLostFoundRoute: ApiLostFoundRoute,
  ApiPvRoute: ApiPvRoute,
  ApiTrafficRoute: ApiTrafficRoute,
  GaresStationRoute: GaresStationRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicDiscordLoginRoute: ApiPublicDiscordLoginRoute,
  ApiPublicDiscordLogoutRoute: ApiPublicDiscordLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
